export {}

// would be generated by sst, but requires `sst build` to be run, which calls out to aws; not great for CI
import 'sst/node/bucket';
import 'sst/node/table';
import 'sst/node/config';

declare module 'sst/node/bucket' {
  export interface BucketResources {
    'aggregator-buffer-store': {
      bucketName: string;
    };
  }
}

declare module 'sst/node/table' {
  export interface TableResources {
    'aggregator-piece-store': {
      tableName: string;
    };
    'aggregator-aggregate-store': {
      tableName: string;
    };
    'aggregator-inclusion-store': {
      tableName: string;
    };
    'deal-tracker-deal-store-v1': {
      tableName: string;
    };
    'dealer-aggregate-store': {
      tableName: string;
    };
  }
}

declare module 'sst/node/config' {
  export interface SecretResources {
    AGGREGATOR_PRIVATE_KEY: {
      value: string
    },
    DEALER_PRIVATE_KEY: {
      value: string
    },
    DEAL_TRACKER_PRIVATE_KEY: {
      value: string
    },
    UCAN_LOG_BASIC_AUTH: {
      value: string
    }
  }
}
