export {}

// would be generated by sst, but requires `sst build` to be run, which calls out to aws; not great for CI
import 'sst/node/bucket';
import 'sst/node/table';
import 'sst/node/config';

declare module 'sst/node/bucket' {
  export interface BucketResources {
    'buffer-store': {
      bucketName: string;
    };
  }
}

declare module 'sst/node/table' {
  export interface TableResources {
    'piece-store': {
      tableName: string;
    };
    'aggregate-store': {
      tableName: string;
    };
    'inclusion-store': {
      tableName: string;
    };
    'deal-store': {
      tableName: string;
    };
  }
}

declare module 'sst/node/config' {
  export interface SecretResources {
    PRIVATE_KEY: {
      value: string
    },
    UCAN_LOG_BASIC_AUTH: {
      value: string
    }
  }
}
