export {}

// would be generated by sst, but requires `sst build` to be run, which calls out to aws; not great for CI
declare module 'sst/node/rds' {
  interface Cluster {
    defaultDatabaseName: string
    secretArn: string
    clusterArn: string
  }

  export interface RDSResources {
    w3filecoinrds: Cluster
  }
}

// would be generated by sst, but requires `sst build` to be run, which calls out to aws; not great for CI
declare module 'sst/node/config' {
  export interface SecretResources {
    PRIVATE_KEY: {
      value: string
    }
  }
}
